%YAML:1.0
fx: 18346.2          # 内参fx(px)
fy: 18215.6          # 内参fy(px)
bx: 0.02             # 基线x(m)
by: 0.00             # 基线y(m)
z_min: 1.0           # 距离下限(m)
z_max: 28.0       # 距离上限(m)
z_ref: 0.0      # 参考距离(m, 0=无穷远)
step: 1.0            # 采样步长(m)
eps_list: [2, 3, 5]  # 像素阈值(px)
